#!/usr/bin/env python3
"""
Offline audio speaker diarization baseline.

Input:
- A mono/stereo PCM WAV (typically 16k mono generated by Sub-Zero).
- Speech segments (start/end seconds) computed by Sub-Zero's VAD (ffmpeg silencedetect).

Output:
- JSON file with the same segments labeled by an integer speaker cluster id.

This is intentionally lightweight: no pyannote/speechbrain, no downloads, no sklearn.
It's meant to be a deterministic "good enough" baseline to support Phase E iteration.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import sys
import wave
from dataclasses import dataclass
from typing import Any, Iterable

import numpy as np


@dataclass(frozen=True)
class Segment:
    start: float
    end: float

    def duration(self) -> float:
        return max(0.0, self.end - self.start)


def _stable_seed(*parts: str) -> int:
    h = hashlib.sha1()
    for p in parts:
        h.update(p.encode("utf-8", errors="ignore"))
        h.update(b"\x00")
    return int.from_bytes(h.digest()[:8], "big", signed=False) & 0x7FFF_FFFF


def read_wav_mono(path: str) -> tuple[np.ndarray, int]:
    with wave.open(path, "rb") as wf:
        n_channels = wf.getnchannels()
        sampwidth = wf.getsampwidth()
        sample_rate = wf.getframerate()
        n_frames = wf.getnframes()
        raw = wf.readframes(n_frames)

    if sampwidth == 2:
        audio = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0
    elif sampwidth == 4:
        audio = np.frombuffer(raw, dtype=np.int32).astype(np.float32) / 2147483648.0
    else:
        raise ValueError(f"unsupported WAV sample width: {sampwidth} bytes")

    if n_channels > 1:
        audio = audio.reshape(-1, n_channels).mean(axis=1)

    return audio, int(sample_rate)


def load_segments(path: str) -> list[Segment]:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError("segments JSON must be a list")
    out: list[Segment] = []
    for item in data:
        if not isinstance(item, dict):
            continue
        start = float(item.get("start", 0.0))
        end = float(item.get("end", 0.0))
        if not (math.isfinite(start) and math.isfinite(end)):
            continue
        if end <= start:
            continue
        out.append(Segment(start=start, end=end))
    out.sort(key=lambda s: (s.start, s.end))
    return out


def hann(n: int) -> np.ndarray:
    if n <= 1:
        return np.ones((n,), dtype=np.float32)
    i = np.arange(n, dtype=np.float32)
    return 0.5 - 0.5 * np.cos((2.0 * np.pi * i) / (n - 1.0))


def zcr(x: np.ndarray) -> float:
    if x.size < 2:
        return 0.0
    s = np.sign(x)
    return float(np.mean(s[1:] != s[:-1]))


def spectral_features(x: np.ndarray, sample_rate: int) -> tuple[float, float, float]:
    # Returns (centroid_hz, bandwidth_hz, rolloff_hz)
    if x.size < 32:
        return 0.0, 0.0, 0.0
    x = x.astype(np.float32, copy=False)
    x = x - float(np.mean(x))
    w = hann(int(x.size))
    xw = x * w
    mag = np.abs(np.fft.rfft(xw))
    if not np.isfinite(mag).all():
        return 0.0, 0.0, 0.0
    total = float(np.sum(mag))
    if total <= 1e-9:
        return 0.0, 0.0, 0.0
    freqs = np.fft.rfftfreq(xw.size, d=1.0 / float(sample_rate)).astype(np.float32)
    centroid = float(np.sum(freqs * mag) / total)
    bandwidth = float(math.sqrt(max(0.0, float(np.sum(((freqs - centroid) ** 2) * mag) / total))))
    cumsum = np.cumsum(mag)
    target = 0.85 * cumsum[-1]
    idx = int(np.searchsorted(cumsum, target))
    idx = max(0, min(idx, freqs.size - 1))
    rolloff = float(freqs[idx])
    return centroid, bandwidth, rolloff


def segment_embedding(audio: np.ndarray, sample_rate: int, seg: Segment) -> np.ndarray | None:
    dur = seg.duration()
    if dur < 0.45:
        return None

    # Sample a few windows inside the segment for stability.
    win_sec = 0.50
    win = int(round(win_sec * sample_rate))
    if win < 256:
        return None

    seg_start = int(max(0.0, seg.start) * sample_rate)
    seg_end = int(min(float(audio.size) / sample_rate, seg.end) * sample_rate)
    if seg_end - seg_start < win:
        # Not enough room for a full window; take what we have if it's still usable.
        if seg_end - seg_start < 512:
            return None
        win = seg_end - seg_start

    n_windows = 3
    if seg_end - seg_start > win:
        stride = (seg_end - seg_start - win) / max(1, n_windows - 1)
        starts = [int(seg_start + i * stride) for i in range(n_windows)]
    else:
        starts = [seg_start]

    feats: list[list[float]] = []
    for s in starts:
        x = audio[s : s + win]
        if x.size < 256:
            continue
        rms = float(math.sqrt(float(np.mean(x * x)) + 1e-12))
        c, b, r = spectral_features(x, sample_rate)
        feats.append([c, b, r, zcr(x), rms])

    if not feats:
        return None
    v = np.array(feats, dtype=np.float32)
    return np.mean(v, axis=0)


def _pairwise_sq_dists(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    # (n,d) and (m,d) -> (n,m)
    aa = np.sum(a * a, axis=1, keepdims=True)
    bb = np.sum(b * b, axis=1, keepdims=True).T
    return aa + bb - 2.0 * (a @ b.T)


def kmeans_fit(
    x: np.ndarray, k: int, rng: np.random.Generator, iters: int = 25, restarts: int = 3
) -> tuple[np.ndarray, np.ndarray, float]:
    n, d = x.shape
    if k <= 1:
        labels = np.zeros((n,), dtype=np.int32)
        center = np.mean(x, axis=0, keepdims=True)
        inertia = float(np.sum((x - center) ** 2))
        return center, labels, inertia

    best_centers: np.ndarray | None = None
    best_labels: np.ndarray | None = None
    best_inertia = float("inf")

    for _ in range(restarts):
        # kmeans++ init
        centers = np.empty((k, d), dtype=np.float32)
        centers[0] = x[int(rng.integers(0, n))]
        closest = _pairwise_sq_dists(x, centers[0:1]).reshape(-1)
        for i in range(1, k):
            probs = np.maximum(closest, 0.0)
            s = float(np.sum(probs))
            if s <= 1e-12:
                centers[i] = x[int(rng.integers(0, n))]
            else:
                probs = probs / s
                centers[i] = x[int(rng.choice(n, p=probs))]
            dist_new = _pairwise_sq_dists(x, centers[i : i + 1]).reshape(-1)
            closest = np.minimum(closest, dist_new)

        labels = np.zeros((n,), dtype=np.int32)
        for _iter in range(iters):
            dists = _pairwise_sq_dists(x, centers)
            new_labels = np.argmin(dists, axis=1).astype(np.int32)
            if np.array_equal(new_labels, labels) and _iter > 0:
                break
            labels = new_labels

            for ci in range(k):
                mask = labels == ci
                if not np.any(mask):
                    centers[ci] = x[int(rng.integers(0, n))]
                else:
                    centers[ci] = np.mean(x[mask], axis=0)

        inertia = float(np.sum((x - centers[labels]) ** 2))
        if inertia < best_inertia:
            best_inertia = inertia
            best_centers = centers.copy()
            best_labels = labels.copy()

    assert best_centers is not None and best_labels is not None
    return best_centers, best_labels, float(best_inertia)


def choose_k_by_elbow(inertias: list[float]) -> int:
    # inertias[0] is k=1
    if len(inertias) <= 1:
        return 1
    # Pick the smallest k where marginal gain drops below 10%.
    for k in range(2, len(inertias) + 1):
        prev = inertias[k - 2]
        cur = inertias[k - 1]
        if prev <= 1e-9:
            return max(1, k - 1)
        gain = (prev - cur) / prev
        if gain < 0.10:
            return max(1, k - 1)
    return len(inertias)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--wav", required=True)
    ap.add_argument("--segments-json", required=True)
    ap.add_argument("--max-speakers", type=int, default=4)
    ap.add_argument("--out-json", required=True)
    args = ap.parse_args(argv)

    wav_path = args.wav
    seg_path = args.segments_json
    out_path = args.out_json
    max_speakers = int(args.max_speakers)
    if max_speakers < 1:
        raise SystemExit("--max-speakers must be >= 1")

    audio, sr = read_wav_mono(wav_path)
    segments = load_segments(seg_path)

    emb: list[np.ndarray] = []
    keep: list[Segment] = []
    for seg in segments:
        v = segment_embedding(audio, sr, seg)
        if v is None:
            continue
        emb.append(v)
        keep.append(seg)

    if not keep:
        payload = {
            "version": "1.0",
            "kind": "audio-diarization",
            "wav": os.path.abspath(wav_path),
            "sample_rate": sr,
            "speakers": 0,
            "segments": [],
        }
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)
            f.write("\n")
        return 0

    x = np.stack(emb, axis=0).astype(np.float32)
    # Standardize for clustering stability.
    mu = np.mean(x, axis=0)
    sigma = np.std(x, axis=0)
    sigma = np.where(sigma < 1e-6, 1.0, sigma)
    xz = (x - mu) / sigma

    n = int(xz.shape[0])
    max_k = int(min(max_speakers, max(1, n)))

    seed = _stable_seed(os.path.abspath(wav_path), str(max_speakers), str(n))
    rng = np.random.default_rng(seed)

    inertias: list[float] = []
    centers_by_k: list[np.ndarray] = []
    labels_by_k: list[np.ndarray] = []
    for k in range(1, max_k + 1):
        centers, labels, inertia = kmeans_fit(xz, k, rng)
        inertias.append(inertia)
        centers_by_k.append(centers)
        labels_by_k.append(labels)

    chosen_k = choose_k_by_elbow(inertias)
    centers = centers_by_k[chosen_k - 1]
    labels = labels_by_k[chosen_k - 1]

    seg_out = []
    for seg, lab in zip(keep, labels, strict=True):
        seg_out.append({"start": seg.start, "end": seg.end, "speaker": int(lab)})

    payload = {
        "version": "1.0",
        "kind": "audio-diarization",
        "wav": os.path.abspath(wav_path),
        "sample_rate": sr,
        "speakers": int(chosen_k),
        "segments": seg_out,
        "stats": {
            "input_segments": len(segments),
            "used_segments": len(keep),
            "seed": seed,
        },
    }

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
        f.write("\n")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except BrokenPipeError:
        raise SystemExit(0)
